DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ITEM_IN_ORDER;

CREATE TABLE USERS (
  ID         INT          NOT NULL AUTO_INCREMENT,
  USERNAME   VARCHAR(16)  NOT NULL,
  PASSWORD   VARCHAR(100) NOT NULL,
  FIRST_NAME VARCHAR(16)  NOT NULL,
  LAST_NAME  VARCHAR(16)  NOT NULL,
  ROLE       VARCHAR(16)  NOT NULL,
  UNIQUE UQ_USER_1 (USERNAME),
  PRIMARY KEY (ID)
);

CREATE TABLE ITEMS (
  ID          INT          NOT NULL AUTO_INCREMENT,
  TITLE       VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  PRICE       INT          NOT NULL,
  ICON        VARCHAR(100),
  UNIQUE UQ_ITEM_1 (TITLE),
  PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
  ID      INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_ODER FOREIGN KEY (USER_ID)
  REFERENCES USERS (ID)
);

CREATE TABLE ITEM_IN_ORDER (
  ITEM_ID  INT NOT NULL,
  ORDER_ID INT NOT NULL,
  PRIMARY KEY (ITEM_ID, ORDER_ID),
  CONSTRAINT FK_ITEM_IN_ORDER_1 FOREIGN KEY (ITEM_ID)
  REFERENCES ITEMS (ID),
  CONSTRAINT FK_ITEM_IN_ORDER_2 FOREIGN KEY (ORDER_ID)
  REFERENCES ORDERS (ID)
);
